# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20170724_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plannedTrips',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
